import type { ChangeEvent, Dispatch, KeyboardEvent, ReactNode, SetStateAction } from 'react';
import type { CodeInfo } from './shared.tsx';
import type { CodeSearchItem, CodeSearchSource } from '../types/search.ts';
import type { RuleSet, NameMap } from '../types/rules.ts';
import type { GroupingResult, PatientInfoInput } from '../types/grouper.ts';
import type { PermutationResult, PermutationGroup } from '../types/single-entry.ts';
import { GroupingTrace } from '../components/GroupingTrace.tsx';
type CodeKind = 'diagnosis' | 'procedure';
interface CodeTag { tag: string; idx?: string }
interface CodeTags { tags: CodeTag[] }
interface PatientField { key: keyof PatientInfoInput; label: string; className: string; control: ReactNode }
interface SingleTabProps {
  searchSource: string;
  lite?: boolean;
  version?: string;
  codeIndexRevision?: number;
  onViewInMdcTree?: (code: string) => void;
}
import { useState, useRef, useEffect, useLayoutEffect, useMemo, useCallback } from 'react';
import { Trash2, ArrowUp } from 'lucide-react';
import { loadRuleSet, loadRuleSetAsync } from '../services/ruleSetLoader.ts';
import { searchCodes } from '../services/CodeSearch';
import { convertGLtoYBCode } from '../services/CodeConversion';
import { buildPatientInfo, groupSingle, groupAllOrders } from '../services/singleEntry';
import { DEFAULT_RULE_VERSION, getVersionDefinition } from '../services/generated/versionRegistry.ts';
import { createEmptyInfo, ensureSingleTrailingEmpty, reorderWithInfos, normalizeCodesAndInfos, namesSignificantlyDiffer } from './shared.tsx';
const createGroupingRequestError = (error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  return {
    drg: null,
    mdc: null,
    adrg: null,
    code: 'ERR',
    error: 'GROUPING_REQUEST_FAILED',
    description: message,
    matchTrace: [{ event: 'transport' as const, error: true, description: message }],
  };
};
const normalizeInfoLength = (infos: CodeInfo[], targetLength: number) => {
  const next = [...infos];
  if (next.length > targetLength) next.splice(targetLength);
  while (next.length < targetLength) next.push(createEmptyInfo());
  return next;
};
// helper for keydown handlers: ignore events generated by an active IME
// composition session.  Browsers may indicate this with `isComposing` on the
// synthetic or native event or by emitting a `Process` key.  The input logic
// should simply return early when the user is still choosing characters.
function isIMEComposing(e: KeyboardEvent<HTMLInputElement> & { isComposing?: boolean }) {
  if (e.isComposing) return true;
  if (e.nativeEvent.isComposing) return true;
  if (e.key === 'Process') return true;
  return false;
}

const EMPTY_RULE_SET: Pick<RuleSet, "loadCCCodes" | "loadMCCCodes" | "loadCCECodes" | "loadYBDiagNames" | "loadYBProcNames" | "isGrayDiag" | "isGrayProc" | "isInvalidDiagnosis" | "isInvalidProcedure"> = Object.freeze({
  loadCCCodes: () => ({}),
  loadMCCCodes: () => ({}),
  loadCCECodes: () => ({}),
  loadYBDiagNames: () => ({}),
  loadYBProcNames: () => ({}),
  isGrayDiag: () => false,
  isGrayProc: () => false,
  isInvalidDiagnosis: () => false,
  isInvalidProcedure: () => false,
});

function getInitialRuleSet(version: string) {
  try {
    return loadRuleSet(version);
  } catch {
    return null;
  }
}

function PatientInfoHeader({ showPatientInfo, onToggle }: { showPatientInfo: boolean; onToggle: () => void }) {
  return (
    <div className="mt-4 flex items-center justify-between cursor-pointer select-none group py-1" onClick={onToggle} role="button" aria-expanded={showPatientInfo}>
      <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-widest">Patient Info</h3>
      <span className="text-gray-500 group-hover:text-gray-300 transition text-xs">{showPatientInfo ? '▲ Hide' : '▼ Show'}</span>
    </div>
  );
}
function ActionButtons({ onGroupSingle, onGroupAllOrders, onClear, permRunning, showAllOrders = true }: { onGroupSingle: () => void; onGroupAllOrders: () => void; onClear: () => void; permRunning: boolean; showAllOrders?: boolean }) {
  return (
    <div className="mt-4 flex gap-2 items-center">
      <button
        onClick={onGroupSingle}
        className="flex-1 whitespace-nowrap bg-blue-600 px-3 py-2 text-sm font-bold text-white rounded-xl hover:bg-blue-700 active:scale-[0.98] transition shadow-md sm:text-base"
      >
        Group Patient
      </button>
      {showAllOrders && (
        <button
          onClick={onGroupAllOrders}
          className="flex-1 bg-gray-700 text-gray-100 py-2 px-3 rounded-xl text-sm font-medium hover:bg-gray-600 active:scale-[0.98] transition border border-gray-600 disabled:opacity-50"
          disabled={permRunning}
          title="Try all diagnosis/procedure orderings and report distinct DRG results"
        >
          {permRunning ? (
            <span className="flex items-center justify-center gap-2">
              <span className="inline-block w-3 h-3 border-2 border-gray-400 border-t-transparent rounded-full animate-spin" />
              Running…
            </span>
          ) : 'All Orders'}
        </button>
      )}
      <button
        onClick={onClear}
        className="px-3 py-2 rounded-xl text-sm font-medium text-red-400 hover:text-red-300 hover:bg-red-900 hover:bg-opacity-30 transition border border-transparent hover:border-red-800"
        title="Clear all inputs"
      >
        Clear
      </button>
    </div>
  );
}
export default function SingleTab({
  searchSource,
  lite = false,
  version = DEFAULT_RULE_VERSION,
  codeIndexRevision = 0,
  onViewInMdcTree,
}: SingleTabProps) {
  const [ruleSetState, setRuleSetState] = useState<{ ruleSet: RuleSet | null; loadedVersion: string | null; loadError: { version: string; error: unknown } | null }>(() => {
    const initialRuleSet = getInitialRuleSet(version);
    return {
      ruleSet: initialRuleSet,
      loadedVersion: initialRuleSet ? version : null,
      loadError: null,
    };
  });
  const { ruleSet: loadedRuleSet, loadedVersion, loadError } = ruleSetState;
  useEffect(() => {
    let active = true;
    loadRuleSetAsync(version).then((nextRuleSet) => {
      if (active) {
        setRuleSetState({ ruleSet: nextRuleSet, loadedVersion: version, loadError: null });
      }
    }).catch((error: unknown) => {
      if (active) {
        setRuleSetState({ ruleSet: null, loadedVersion: version, loadError: { version, error } });
      }
    });
    return () => { active = false; };
  }, [version]);
  const ruleSet = useMemo(() => (
    loadedVersion === version ? loadedRuleSet : getInitialRuleSet(version)
  ), [loadedRuleSet, loadedVersion, version]);
  const effectiveRuleSet = ruleSet || EMPTY_RULE_SET;
  const patientInfoFieldGroups = useMemo(() => getVersionDefinition(version).patientInfo, [version]);
  const { loadCCCodes, loadMCCCodes, loadCCECodes, loadYBDiagNames, loadYBProcNames, isGrayDiag, isGrayProc, isInvalidDiagnosis, isInvalidProcedure } = effectiveRuleSet;
  const ybDiagNames = useMemo(() => loadYBDiagNames(), [loadYBDiagNames]);
  const ybProcNames = useMemo(() => loadYBProcNames(), [loadYBProcNames]);
  const ccIndex = useMemo(() => loadCCCodes(), [loadCCCodes]);
  const mccIndex = useMemo(() => loadMCCCodes(), [loadMCCCodes]);
  const excludeIndex = useMemo(() => loadCCECodes(), [loadCCECodes]);
  const getCodeTagAndIndex = useCallback((code: string, kind: CodeKind = 'diagnosis', idx = 0): CodeTags | null => {
    if (!code) return null;
    const normalizedCode = searchSource === 'GL' ? convertGLtoYBCode(code, kind === 'procedure', version) : code;
    const tags: CodeTag[] = [];

    if (kind === 'procedure') {
      if (isInvalidProcedure(normalizedCode)) tags.push({ tag: 'INVALID' });
      if (isGrayProc(normalizedCode)) tags.push({ tag: 'GRAY' });
      if (!tags.length) return null;
      return { tags };
    }

    // diagnosis path
    if (isInvalidDiagnosis(normalizedCode)) tags.push({ tag: 'INVALID' });
    if (isGrayDiag(normalizedCode)) tags.push({ tag: 'GRAY' });
    if (idx === 0) {
      if (Object.hasOwn(excludeIndex, normalizedCode) && excludeIndex[normalizedCode]) tags.push({ tag: 'CCE', idx: excludeIndex[normalizedCode] });
    } else {
      if (Object.hasOwn(mccIndex, normalizedCode) && mccIndex[normalizedCode]) tags.push({ tag: 'MCC', idx: mccIndex[normalizedCode] });
      if (Object.hasOwn(ccIndex, normalizedCode) && ccIndex[normalizedCode]) tags.push({ tag: 'CC', idx: ccIndex[normalizedCode] });
    }

    if (!tags.length) return null;
    return { tags };
  }, [ccIndex, mccIndex, excludeIndex, searchSource, version, isGrayDiag, isGrayProc, isInvalidDiagnosis, isInvalidProcedure]);

  const [diagnoses, setDiagnoses] = useState(['']);
  const [procedures, setProcedures] = useState(['']);
  const [result, setResult] = useState<GroupingResult | null>(null);
  const [hasGrouped, setHasGrouped] = useState(false);
  const [patientGender, setPatientGender] = useState('');
  const [patientAge, setPatientAge] = useState('');
  const [patientAgeInDays, setPatientAgeInDays] = useState('');
  const [patientBirthWeight, setPatientBirthWeight] = useState('');
  const [patientAdmissionWeight, setPatientAdmissionWeight] = useState('');
  const [patientDischargeStatus, setPatientDischargeStatus] = useState('');
  const [patientNewTechnique, setPatientNewTechnique] = useState<boolean | string>('');
  const [patientIntensiveCare, setPatientIntensiveCare] = useState<boolean | string>('');
  const [patientIcuHours, setPatientIcuHours] = useState('');
  const [patientCrrtHours, setPatientCrrtHours] = useState('');
  const [patientLengthOfStay, setPatientLengthOfStay] = useState('');
  const [patientDaySurgery, setPatientDaySurgery] = useState<boolean | string>('');
  const [showPatientInfo, setShowPatientInfo] = useState(false);
  const [diagnosisInfos, setDiagnosisInfos] = useState<CodeInfo[]>([]);
  const [procedureInfos, setProcedureInfos] = useState<CodeInfo[]>([createEmptyInfo()]);
  const [permResults, setPermResults] = useState<PermutationResult | null>(null);
  const [permRunning, setPermRunning] = useState(false);
  const diagInputRefs = useRef<(HTMLInputElement | null)[]>([]);
  const procInputRefs = useRef<(HTMLInputElement | null)[]>([]);
  const prevSearchContextRef = useRef<string | null>(null);
  const searchSourceRef = useRef(searchSource);
  const groupRequestRef = useRef(0);
  const resultRef = useRef<HTMLDivElement | null>(null);
  const setDiagRef = (el: HTMLInputElement | null, idx: number) => { diagInputRefs.current[idx] = el; };
  const setProcRef = (el: HTMLInputElement | null, idx: number) => { procInputRefs.current[idx] = el; };
  const focusDiagAt = (idx: number) => { const el = diagInputRefs.current[idx]; if (el) el.focus(); };
  const focusProcAt = (idx: number) => { const el = procInputRefs.current[idx]; if (el) el.focus(); };
  const getPatientInfo = useCallback(() => (
    buildPatientInfo({
        gender: patientGender,
        age: patientAge,
        ageInDays: patientAgeInDays,
        birthWeight: patientBirthWeight,
        admissionWeight: patientAdmissionWeight,
        dischargeStatus: patientDischargeStatus,
        newTechnique: patientNewTechnique,
        intensiveCare: patientIntensiveCare,
        icuHours: patientIcuHours,
        crrtHours: patientCrrtHours,
        lengthOfStay: patientLengthOfStay,
        daySurgery: patientDaySurgery,
      })
  ), [patientGender, patientAge, patientAgeInDays, patientBirthWeight, patientAdmissionWeight, patientDischargeStatus, patientNewTechnique, patientIntensiveCare, patientIcuHours, patientCrrtHours, patientLengthOfStay, patientDaySurgery]);
  const handlePatientAgeChange = (value: string) => {
    setPatientAge(value);
    if (value.trim() !== '') setPatientAgeInDays('');
  };
  const handlePatientAgeInDaysChange = (value: string) => {
    setPatientAgeInDays(value);
    if (value.trim() !== '') setPatientAge('');
  };

  useEffect(() => { searchSourceRef.current = searchSource; }, [searchSource]);

  const principalDiagnosisTag = useMemo(() => {
    const principal = diagnoses[0];
    return principal ? getCodeTagAndIndex(principal, 'diagnosis', 0) : null;
  }, [diagnoses, getCodeTagAndIndex]);

  const principalDiagnosisCCEId = useMemo(() => {
    if (!principalDiagnosisTag) return null;
    const tags = principalDiagnosisTag.tags;
    const cce = tags.find((t) => t.tag === 'CCE');
    return cce ? cce.idx : null;
  }, [principalDiagnosisTag]);

  const handleListBlur = (kind: CodeKind, idx: number) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const setCodes = isDiagnosis ? setDiagnoses : setProcedures;
    const setInfos = isDiagnosis ? setDiagnosisInfos : setProcedureInfos;
    const searchType = isDiagnosis ? 'Diagnosis' : 'Procedure';
    setTimeout(() => {
      try {
        const value = (codes[idx] ?? '').trim();
        const patch: Partial<CodeInfo> = {};
        if (value) {
          const results = searchCodes(value, searchType, searchSourceRef.current, version);
          const exact = results.find(item => item.code.toLowerCase() === value.toLowerCase());
          if (exact) {
            patch.desc = exact.name;
            patch.type = exact.type;
          } else {
            patch.desc = '';
          }
        } else {
          patch.desc = '';
        }
        setInfos(prev => {
          const next = [...prev];
          if (!next[idx]) next[idx] = createEmptyInfo();
          next[idx] = { ...next[idx], ...patch, showDropdown: false };
          return next;
        });
      } catch {
        setInfos(prev => {
          const next = [...prev];
          if (next[idx]) next[idx] = { ...next[idx], showDropdown: false };
          return next;
        });
        return;
      }
      setCodes(prev => {
        const normalizedCodes = ensureSingleTrailingEmpty(prev);
        setInfos(prevInfos => normalizeInfoLength(prevInfos, normalizedCodes.length));
        return normalizedCodes;
      });
    }, 150);
  };


  const updateListInfo = useCallback((kind: CodeKind, idx: number, updater: (info: CodeInfo) => CodeInfo) => {
    const setInfos = kind === 'diagnosis' ? setDiagnosisInfos : setProcedureInfos;
    setInfos(prev => {
      const next = [...prev];
      const current = next[idx] || createEmptyInfo();
      next[idx] = updater(current);
      return next;
    });
  }, [setDiagnosisInfos, setProcedureInfos]);

  const handleListKeyDown = (kind: CodeKind, e: KeyboardEvent<HTMLInputElement>, idx: number) => {
    // IME composition (pinyin) sends intermediary key events that should not
    // trigger navigation or selection.  Early-out when we detect an active
    // composition phase; this fixes complaints from Chinese users.
    if (isIMEComposing(e)) return;

    const isDiagnosis = kind === 'diagnosis';
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const setInfos = isDiagnosis ? setDiagnosisInfos : setProcedureInfos;
    const focusAt = isDiagnosis ? focusDiagAt : focusProcAt;
    const setCodes = isDiagnosis ? setDiagnoses : setProcedures;
    const idPrefix = isDiagnosis ? 'diag' : 'proc';
    const selectFn = (index: number, code: string, desc: string, type: string) => handleListSelect(kind, index, code, desc, type);

    const info: Partial<CodeInfo> = infos[idx] || {};
    const results = (info.searchResults || []).slice(0, 20);
    const count = results.length;
    const highlighted = info.highlightedIndex ?? -1;
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (!count) return;
      const next = highlighted < 0 || highlighted >= count - 1 ? 0 : highlighted + 1;
      setInfos(prev => {
        const a = [...prev];
        if (!a[idx]) a[idx] = createEmptyInfo({ showDropdown: true });
        a[idx] = { ...a[idx], highlightedIndex: next, showDropdown: true };
        return a;
      });
      setTimeout(() => {
        const el = document.getElementById(`${idPrefix}-${idx}-item-${next}`);
        el?.scrollIntoView({ block: 'nearest' });
      }, 0);
      return;
    }
    if (e.key === 'ArrowUp') {
      e.preventDefault();
      if (!count) return;
      const next = (highlighted <= 0) ? count - 1 : highlighted - 1;
      setInfos(prev => {
        const a = [...prev];
        if (!a[idx]) a[idx] = createEmptyInfo({ showDropdown: true });
        a[idx] = { ...a[idx], highlightedIndex: next, showDropdown: true };
        return a;
      });
      setTimeout(() => {
        const el = document.getElementById(`${idPrefix}-${idx}-item-${next}`);
        el?.scrollIntoView({ block: 'nearest' });
      }, 0);
      return;
    }
    if (e.key === 'Escape') {
      e.preventDefault();
      setInfos(prev => {
        const a = [...prev];
        if (a[idx]) { a[idx].showDropdown = false; a[idx].highlightedIndex = -1; }
        return a;
      });
      return;
    }
    if (e.key === 'Enter') {
      e.preventDefault();
      if (info.searchResults && info.searchResults.length > 0) {
        const selIndex = highlighted >= 0 ? highlighted : 0;
        const item = info.searchResults[selIndex];
        if (item) {
          selectFn(idx, item.code, item.name, item.type);
          setTimeout(() => focusAt(idx + 1), 50);
          return;
        }
      }
      setCodes(prev => {
        const n = ensureSingleTrailingEmpty(prev);
        setTimeout(() => focusAt(idx + 1), 50);
        return n;
      });
    }
  };

  const handleListRemove = (kind: CodeKind, index: number) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const setCodes = isDiagnosis ? setDiagnoses : setProcedures;
    const setInfos = isDiagnosis ? setDiagnosisInfos : setProcedureInfos;
    const nextCodes = [...codes];
    nextCodes.splice(index, 1);
    const normalized = ensureSingleTrailingEmpty(nextCodes);
    setCodes(normalized);
    setInfos((prev) => {
      const arr = [...prev];
      if (index >= 0 && index < arr.length) arr.splice(index, 1);
      return normalizeInfoLength(arr, normalized.length);
    });
  };

  // Move the given entry up to be the principal (index 0).
  const handleMoveToPrincipal = (kind: CodeKind, index: number) => {
    if (index === 0) return;
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const setCodes = isDiagnosis ? setDiagnoses : setProcedures;
    const setInfos = isDiagnosis ? setDiagnosisInfos : setProcedureInfos;
    const focusAt = isDiagnosis ? focusDiagAt : focusProcAt;

    setCodes(prev => {
      const { normalized } = reorderWithInfos(prev, infos, index, 0);
      return normalized;
    });
    setInfos(prev => {
      const { newInfos } = reorderWithInfos(codes, prev, index, 0);
      return newInfos;
    });

    // move focus to the new principal input so the user can continue typing
    setTimeout(() => focusAt(0), 50);
  };

  const handleListChange = (kind: CodeKind, index: number, val: string) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const searchType = isDiagnosis ? 'Diagnosis' : 'Procedure';
    const prevCodes = [...codes];
    const prevInfos = [...infos];
    prevCodes[index] = val;
    if (val.trim()) {
      const res = searchCodes(val.trim(), searchType, searchSourceRef.current, version);
      const existingDesc = (prevInfos[index] && prevInfos[index].desc) ? prevInfos[index].desc : '';
      prevInfos[index] = res.length ? createEmptyInfo({ desc: existingDesc, type: res[0]!.type, searchResults: res, showDropdown: true }) : createEmptyInfo({ desc: existingDesc });
    } else {
      prevInfos[index] = createEmptyInfo();
    }
    const normalized = normalizeCodesAndInfos(prevCodes, prevInfos);
    if (isDiagnosis) {
      setDiagnoses(normalized.codes);
      setDiagnosisInfos(normalized.infos);
    } else {
      setProcedures(normalized.codes);
      setProcedureInfos(normalized.infos);
    }
  };

  const handleListSelect = (kind: CodeKind, index: number, code: string, desc: string, type: string) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const prevCodes = [...codes];
    const prevInfos = [...infos];
    prevCodes[index] = code;
    prevInfos[index] = createEmptyInfo({ desc, type });
    const normalized = normalizeCodesAndInfos(prevCodes, prevInfos);
    if (isDiagnosis) {
      setDiagnoses(normalized.codes);
      setDiagnosisInfos(normalized.infos);
    } else {
      setProcedures(normalized.codes);
      setProcedureInfos(normalized.infos);
    }
  };
  const handleGroupSingle = useCallback(async () => {
    const requestId = ++groupRequestRef.current;
    const info = getPatientInfo();
    try {
      const out = await groupSingle(diagnoses, procedures, info, searchSource, version);
      if (requestId !== groupRequestRef.current) return;
      setHasGrouped(true);
      setPermResults(null);
      setPermRunning(false);
      setResult({
        ...out.finalRes,
        diagnoses: out.diagnoses,
        procedures: out.procedures,
        diagnosesConverted: out.diagnosesConverted,
        proceduresConverted: out.proceduresConverted,
        conversionApplied: out.conversionApplied,
        patientInfo: out.patientInfo
      });
    } catch (error) {
      if (requestId !== groupRequestRef.current) return;
      setPermResults(null);
      setPermRunning(false);
      setResult(createGroupingRequestError(error));
    }
  }, [diagnoses, procedures, getPatientInfo, searchSource, version]);
  const handleGroupSingleRef = useRef(handleGroupSingle);
  useLayoutEffect(() => {
    handleGroupSingleRef.current = handleGroupSingle;
  }, [handleGroupSingle]);

  const previousGroupingContextRef = useRef({ version, searchSource });
  useLayoutEffect(() => {
    const previous = previousGroupingContextRef.current;
    previousGroupingContextRef.current = { version, searchSource };
    if (previous.version === version && previous.searchSource === searchSource) return;

    // Invalidate before paint, including the first request before hasGrouped is true.
    groupRequestRef.current += 1;
    // Keep displayed results until replacement; an invalidated All Orders run must stop spinning.
    // eslint-disable-next-line react-hooks/set-state-in-effect -- The invalidated request can no longer reset its running state.
    setPermRunning(false);
    if (previous.version !== version && hasGrouped) handleGroupSingleRef.current();
  }, [version, searchSource, hasGrouped]);

  useEffect(() => {
    if (!result || !resultRef.current) return undefined;
    const frame = requestAnimationFrame(() => {
      const element = resultRef.current;
      if (!element) return;
      element.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
      element.focus({ preventScroll: true });
    });
    return () => cancelAnimationFrame(frame);
  }, [result]);

  const handleFlushAll = () => {
    groupRequestRef.current += 1;
    setHasGrouped(false);
    setDiagnoses(['']);
    setProcedures(['']);
    setDiagnosisInfos([createEmptyInfo()]);
    setProcedureInfos([createEmptyInfo()]);
    setPatientGender('');
    setPatientAge('');
    setPatientAgeInDays('');
    setPatientBirthWeight('');
    setPatientAdmissionWeight('');
    setPatientDischargeStatus('');
    setPatientNewTechnique('');
    setPatientIntensiveCare('');
    setPatientIcuHours('');
    setPatientCrrtHours('');
    setPatientLengthOfStay('');
    setPatientDaySurgery('');
    setShowPatientInfo(false);
    setResult(null);
    setPermResults(null);
    setPermRunning(false);
  };
  const handleFlushAllConfirm = () => {
    try {
      const ok = window.confirm('Flush all inputs? This will clear diagnoses, procedures, search state, and reset patient info. Continue?');
      if (!ok) return;
    } catch {
      // ignore confirm API failures
    }
    handleFlushAll();
  };
  const handleGroupAllOrders = async () => {
    const requestId = ++groupRequestRef.current;
    setResult(null);
    setPermRunning(true);
    setPermResults(null);
    const info = getPatientInfo();
    try {
      const out = await groupAllOrders(diagnoses, procedures, info, searchSource, version);
      if (requestId !== groupRequestRef.current) return;
      setPermResults(out);
      setPermRunning(false);
    } catch (error) {
      if (requestId !== groupRequestRef.current) return;
      const failed = createGroupingRequestError(error);
      setPermResults({ totalCombos: 0, processed: 0, results: [], error: failed.error, description: failed.description });
      setPermRunning(false);
    }
  };

  useEffect(() => {
    const searchContext = `${version}:${searchSource}:${codeIndexRevision}`;
    if (prevSearchContextRef.current === searchContext) return;
    prevSearchContextRef.current = searchContext;

    const refreshInfosForSource = (codes: string[], infos: CodeInfo[], setInfos: Dispatch<SetStateAction<CodeInfo[]>>, searchType: string) => {
      const nextInfos = normalizeInfoLength(infos, codes.length).map((info, idx) => {
        const code = (codes[idx] ?? '').trim();
        if (!code) return createEmptyInfo();
        try {
          const results = searchCodes(code, searchType, searchSource, version);
          const exact = results.find((item) => item.code.toLowerCase() === code.toLowerCase());
          if (!exact) return createEmptyInfo({ desc: '', type: '' });
          return createEmptyInfo({
            ...info,
            desc: exact.name,
            type: exact.type,
            searchResults: [],
            showDropdown: false,
            highlightedIndex: -1
          });
        } catch {
          return createEmptyInfo({
            ...info,
            searchResults: [],
            showDropdown: false,
            highlightedIndex: -1
          });
        }
      });
      setInfos(nextInfos);
    };

    refreshInfosForSource(diagnoses, diagnosisInfos, setDiagnosisInfos, 'Diagnosis');
    refreshInfosForSource(procedures, procedureInfos, setProcedureInfos, 'Procedure');
  }, [searchSource, version, codeIndexRevision, diagnoses, procedures, diagnosisInfos, procedureInfos]);

  const patientInfoFields: PatientField[] = [
    {
      key: 'gender',
      label: 'Gender',
      className: '',
      control: (
        <select value={patientGender} onChange={(e) => setPatientGender(e.target.value)} className="mt-1 w-full p-2 border dark-border rounded">
          <option value="">Not set</option>
          <option value="1">Male</option>
          <option value="2">Female</option>
        </select>
      )
    },
    {
      key: 'dischargeStatus',
      label: 'Discharge Status',
      className: '',
      control: (
        <select value={patientDischargeStatus} onChange={(e) => setPatientDischargeStatus(e.target.value)} className="mt-1 w-full p-2 border dark-border rounded">
          <option value="">Not set</option>
          <option value="alive">Alive</option>
          <option value="5">Dead</option>
        </select>
      )
    },
    {
      key: 'age',
      label: 'Age (years)',
      className: '',
      control: <input type="number" min="0" step="1" value={patientAge} onChange={(e) => handlePatientAgeChange(e.target.value)} placeholder="e.g. 30" className="mt-1 w-full p-2 border dark-border rounded" />
    },
    {
      key: 'ageInDays',
      label: 'Age (days)',
      className: '',
      control: <input type="number" min="0" max="365" step="1" value={patientAgeInDays} onChange={(e) => handlePatientAgeInDaysChange(e.target.value)} placeholder="e.g. 20" className="mt-1 w-full p-2 border dark-border rounded" />
    },
    {
      key: 'birthWeight',
      label: 'Birth weight (grams)',
      className: '',
      control: <input type="number" min="1" step="1" value={patientBirthWeight} onChange={(e) => setPatientBirthWeight(e.target.value)} placeholder="e.g. 3200" className="mt-1 w-full p-2 border dark-border rounded" />
    },
    {
      key: 'admissionWeight',
      label: 'Admission weight (grams)',
      className: '',
      control: <input type="number" min="1" step="1" value={patientAdmissionWeight} onChange={(e) => setPatientAdmissionWeight(e.target.value)} placeholder="e.g. 3200" className="mt-1 w-full p-2 border dark-border rounded" />
    },
    {
      key: 'icuHours',
      label: 'ICU duration (hours)',
      className: '',
      control: <input type="number" min="0" step="1" value={patientIcuHours} onChange={(e) => setPatientIcuHours(e.target.value)} placeholder="e.g. 120" className="mt-1 w-full p-2 border dark-border rounded" />
    },
    {
      key: 'crrtHours',
      label: 'CRRT duration (hours)',
      className: '',
      control: <input type="number" min="0" step="1" value={patientCrrtHours} onChange={(e) => setPatientCrrtHours(e.target.value)} placeholder="e.g. 24" className="mt-1 w-full p-2 border dark-border rounded" />
    },
    {
      key: 'lengthOfStay',
      label: 'Length of stay (days)',
      className: '',
      control: <input type="number" min="0" step="1" value={patientLengthOfStay} onChange={(e) => setPatientLengthOfStay(e.target.value)} placeholder="e.g. 7" className="mt-1 w-full p-2 border dark-border rounded" />
    }
  ];

  const renderPatientInfoField = (field: PatientField) => (
    <div key={field.label} className={field.className}>
      <label className="block text-sm text-gray-300 mb-1">{field.label}</label>
      {field.control}
    </div>
  );

  const renderPatientInfoPanel = () => {
    const patientInfoFieldKeys = new Set<string>([
      ...patientInfoFieldGroups.basic,
      ...patientInfoFieldGroups.advanced,
    ]);
    const fieldsByKey = new Map(patientInfoFields.map((field) => [field.key, field]));
    const visibleFields = [
      ...patientInfoFieldGroups.basic,
      ...patientInfoFieldGroups.advanced,
    ]
      .map((key) => fieldsByKey.get(key))
      .filter((field): field is PatientField => Boolean(field));
    const visibleCheckboxes = [
      {
        key: 'newTechnique',
        id: 'newtechnique-checkbox',
        checked: patientNewTechnique,
        onChange: (e: ChangeEvent<HTMLInputElement>) => setPatientNewTechnique(e.target.checked),
        label: 'New Technique (新技术)',
      },
      {
        key: 'intensiveCare',
        id: 'intensive-care-checkbox',
        checked: patientIntensiveCare,
        onChange: (e: ChangeEvent<HTMLInputElement>) => setPatientIntensiveCare(e.target.checked),
        label: 'Intensive care (重症监护)',
      },
      {
        key: 'daySurgery',
        id: 'day-surgery-checkbox',
        checked: patientDaySurgery,
        onChange: (e: ChangeEvent<HTMLInputElement>) => setPatientDaySurgery(e.target.checked),
        label: 'Day surgery (日间手术)',
      },
    ].filter(({ key }) => patientInfoFieldKeys.has(key));
    return (
      <div className="mt-2 p-4 border dark-border rounded-lg dark-surface">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-3 gap-y-3">
          {visibleFields.map(renderPatientInfoField)}
          {visibleCheckboxes.length > 0 && (
            <div className="col-span-full flex flex-wrap items-center gap-x-6 gap-y-2 pt-1">
              {visibleCheckboxes.map((checkbox) => (
                <label key={checkbox.id} htmlFor={checkbox.id} className="inline-flex items-center text-sm text-gray-300 select-none cursor-pointer">
                  <input
                    type="checkbox"
                    id={checkbox.id}
                    checked={!!checkbox.checked}
                    onChange={checkbox.onChange}
                    className="mr-2 w-4 h-4"
                  />
                  <span>{checkbox.label}</span>
                </label>
              ))}
            </div>
          )}
        </div>
      </div>
    );
  };

  const renderCodeTagBadge = (tagInfo: CodeTags | null, principalCCEId: string | null | undefined, compact = false) => {
    if (!tagInfo) return null;
    const tags = tagInfo.tags;
    const wrapperClass = compact ? 'flex flex-wrap items-center gap-1' : 'flex flex-wrap items-center gap-2';
    const base = compact ? 'flex-shrink-0 px-2 py-0.5 rounded font-bold text-xs border ' : 'text-xs px-2 py-1 rounded font-bold border ';

    return (
      <span className={wrapperClass}>
        {tags.map((tagItem, index) => {
          const title = tagItem.tag === 'CCE' ? 'In CCE List' : tagItem.tag;
          const isPrincipalCCE = (tagItem.tag === 'MCC' || tagItem.tag === 'CC') && principalCCEId != null && tagItem.idx && tagItem.idx === principalCCEId;
          const tagClasses: Record<string, string> = {
            INVALID: 'bg-red-100 border-red-300 text-red-700',
            GRAY: 'bg-amber-100 border-amber-300 text-amber-700',
            MCC: isPrincipalCCE ? 'bg-opacity-30 bg-gray-600 text-gray-200 border-gray-500' : 'bg-error border-error text-error',
            CC: isPrincipalCCE ? 'bg-opacity-30 bg-gray-600 text-gray-200 border-gray-500' : 'bg-warning border-warning text-warning'
          };
          const classes = base + (tagClasses[tagItem.tag] || 'bg-opacity-30 bg-gray-600 text-gray-200 border-gray-500');
          return (
            <span key={`${tagItem.tag}-${index}`} className={classes} title={title} aria-label={title}>
              {tagItem.tag}{tagItem.idx ? ` #${tagItem.idx}` : ''}
            </span>
          );
        })}
      </span>
    );
  };

  const getYBPreview = useCallback((item: Pick<CodeSearchItem, "code" | "name" | "source">, isProcedure: boolean, ybNames: NameMap) => {
    const preview = { showYB: false, ybCode: '', ybName: '', hasDifferentCode: false, hasDifferentName: false };
    try {
      if ((searchSource === 'GL' || item.source === 'GL') && item.code) {
        preview.ybCode = convertGLtoYBCode(item.code, isProcedure, version);
        if (preview.ybCode) {
          preview.ybName = ybNames[preview.ybCode] || '';
          preview.hasDifferentCode = preview.ybCode !== item.code;
          preview.hasDifferentName = !!preview.ybName && !!item.name && namesSignificantlyDiffer(item.name, preview.ybName);
          preview.showYB = preview.hasDifferentCode || preview.hasDifferentName;
        }
      }
    } catch {
      preview.showYB = false;
    }
    return preview;
  }, [searchSource, version]);

  const renderSearchDropdownItem = ({ kind, idx, i, item, highlightedIndex, isDiagnosis, principalCCEId, ybNames }: { kind: CodeKind; idx: number; i: number; item: CodeSearchItem; highlightedIndex: number; isDiagnosis: boolean; principalCCEId: string | null | undefined; ybNames: NameMap }) => {
    const tagInfo = getCodeTagAndIndex(item.code, isDiagnosis ? 'diagnosis' : 'procedure', idx);
    const { showYB, ybCode, ybName, hasDifferentCode, hasDifferentName } = getYBPreview(item, !isDiagnosis, ybNames);
    const tags = tagInfo?.tags ?? [];
    const isGray = tags.some((t) => t.tag === 'GRAY');
    const isInvalid = tags.some((t) => t.tag === 'INVALID');
    return (
      <div
        id={`${isDiagnosis ? 'diag' : 'proc'}-${idx}-item-${i}`}
        key={item.code + i}
        className={`px-3 py-2 cursor-pointer text-sm flex flex-col gap-1 transition border-l-2 ${highlightedIndex === i ? 'bg-blue-600 bg-opacity-20 border-blue-400' : 'border-transparent hover:bg-gray-700 hover:bg-opacity-60'}`}
        aria-selected={highlightedIndex === i}
        onMouseDown={() => handleListSelect(kind, idx, item.code, item.name, item.type)}
        onMouseEnter={() => updateListInfo(kind, idx, info => ({ ...info, showDropdown: true, highlightedIndex: i }))}
        onMouseLeave={() => updateListInfo(kind, idx, info => ({ ...info, highlightedIndex: -1 }))}
      >
        <div className="flex items-baseline gap-2 flex-wrap">
          <span className={`font-mono font-bold flex-shrink-0 ${isInvalid ? 'text-red-300' : isGray ? 'text-amber-300' : 'text-blue-400'}`}>{item.code}</span>
          <span className="text-gray-200">{item.name}</span>
          {renderCodeTagBadge(tagInfo, principalCCEId, true)}
          {showYB && (
            <>
              <span className="text-gray-600">→</span>
              {hasDifferentCode && <span className="font-mono text-xs text-gray-400">{ybCode}</span>}
              {hasDifferentName && <span className="text-xs text-gray-500">{ybName}</span>}
            </>
          )}
        </div>
      </div>
    );
  };

  const renderCodeColumn = (kind: CodeKind) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const title = isDiagnosis ? 'Diagnoses' : 'Procedures';
    const principalCCEId = principalDiagnosisCCEId;
    const placeholderFor = (idx: number) => {
      if (isDiagnosis) return idx === 0 ? 'Principal Diagnosis (e.g. G40.909)' : 'Secondary Diagnosis';
      return idx === 0 ? 'Principal Procedure (e.g. 00.10)' : 'Procedure Code (e.g. 00.10)';
    };
    const setRef = isDiagnosis ? setDiagRef : setProcRef;
    const ybNames = isDiagnosis ? ybDiagNames : ybProcNames;

    return (
      <div className={`space-y-4 p-4 md:p-6 box-border ${isDiagnosis ? 'md:pr-8 md:border-r md:border-gray-200' : ''}`}>
        <div className={isDiagnosis ? 'flex justify-between items-end' : 'flex items-center justify-between'}><h2 className="text-xl font-bold text-gray-100">{title}</h2></div>
        {codes.map((code, idx) => {
          const info = infos[idx];
          const entryName = info?.desc || '';
          const tagInfo = getCodeTagAndIndex(code, isDiagnosis ? 'diagnosis' : 'procedure', idx);
          const tags = tagInfo?.tags ?? [];
          const isCodeGray = tags.some((t) => t.tag === 'GRAY');
          const isCodeInvalid = tags.some((t) => t.tag === 'INVALID');
          const inputYB = getYBPreview({ code, name: entryName, source: searchSource as CodeSearchSource }, !isDiagnosis, ybNames);
          return (
            <div
              key={idx}
              data-idx={idx}
              className="flex flex-col gap-1 relative"
            >
              <div className="flex gap-2 items-center">
                <div className="flex-1 min-w-0 flex flex-col md:flex-row md:items-center gap-2">
                  <input
                    type="text"
                    placeholder={placeholderFor(idx)}
                    className={`flex-1 min-w-[13ch] p-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none ${isCodeGray ? 'text-amber-300 border-amber-400' : ''} ${isCodeInvalid ? 'text-red-300 border-red-400' : ''}`}
                    value={code}
                    onChange={(e) => handleListChange(kind, idx, e.target.value)}
                    ref={(el) => setRef(el, idx)}
                    onKeyDown={(e) => handleListKeyDown(kind, e, idx)}
                    autoComplete="off"
                    onFocus={() => updateListInfo(kind, idx, info => ({ ...info, showDropdown: true }))}
                    onBlur={() => handleListBlur(kind, idx)}
                  />
                  {(!!info?.desc || !!tagInfo || inputYB.showYB) && (
                    <div className="flex flex-wrap items-center gap-1 mt-1 md:mt-0">
                      {info?.desc && <span className="text-xs text-gray-300 dark-surface-2 p-1 rounded border dark-border break-words max-w-full">{info.desc}</span>}
                      {renderCodeTagBadge(tagInfo, principalCCEId)}
                      {inputYB.showYB && (
                        <>
                          <span className="text-gray-600">→</span>
                          {inputYB.hasDifferentCode && <span className="font-mono text-xs text-gray-400">{inputYB.ybCode}</span>}
                          {inputYB.hasDifferentName && <span className="text-xs text-gray-500">{inputYB.ybName}</span>}
                        </>
                      )}
                    </div>
                  )}
                </div>
                {idx > 0 && (
                  <button
                    onClick={() => handleMoveToPrincipal(kind, idx)}
                    className="p-2 text-blue-300 hover:bg-blue-700 hover:bg-opacity-50 rounded-sm transition"
                    aria-label={`Make ${isDiagnosis ? 'diagnosis' : 'procedure'} principal`}
                    title="Make principal"
                  >
                    <ArrowUp size={14} />
                  </button>
                )}
                <button
                  onClick={() => handleListRemove(kind, idx)}
                  className="p-2 text-red-400 hover:bg-error hover:bg-opacity-50 rounded-sm transition"
                  aria-label={`Remove ${isDiagnosis ? 'diagnosis' : 'procedure'}`}
                >
                  <Trash2 size={14} />
                </button>
              </div>
              {info?.showDropdown && info.searchResults.length > 0 && (
                <div className="absolute z-10 top-full left-0 w-full bg-gray-900 border border-gray-700 rounded shadow-xl max-h-64 overflow-auto">
                  {info.searchResults.slice(0, 20).map((item, i) => renderSearchDropdownItem({
                    kind,
                    idx,
                    i,
                    item,
                    highlightedIndex: info.highlightedIndex,
                    isDiagnosis,
                    principalCCEId,
                    ybNames
                  }))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    );
  };

  const renderPermutationCard = (r: PermutationGroup, idx: number) => (
    <div key={idx} className="p-2 border dark-border rounded dark-surface-2">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="font-mono font-bold text-lg text-blue-400">{r.summary.drg || r.summary.key}</div>
          <div className="text-sm text-gray-200">{r.summary.description || '-'}</div>
        </div>
        <div className="flex items-center gap-2">
          {r.summary.weight != null && <div className="text-sm font-mono font-semibold text-blue-300">{r.summary.weight === '/' ? '特殊支付' : r.summary.weight}</div>}
          {r.summary.weightTier2 != null && <div className="text-sm font-mono font-semibold text-yellow-300">{r.summary.weightTier2 === '/' ? '特殊支付' : r.summary.weightTier2}</div>}
        </div>
      </div>
      <div className="text-xs mt-1 text-gray-400">Examples ({r.examples.length}):</div>
      <div className="text-xs text-gray-300">
        {r.examples.slice(0, 3).map((ex, i) => {
          const pd = ex.diagnoses[0] || '';
          const pp = ex.procedures[0] || '';
          return (
            <div key={i} className="truncate">diag: [{pd}] proc: [{pp}]</div>
          );
        })}
      </div>
    </div>
  );
  const currentLoadError = loadError?.version === version ? loadError.error : null;
  const loadErrorMessage = currentLoadError instanceof Error ? currentLoadError.message : String(currentLoadError || '');
  const resultCode = result?.drg || result?.code;
  const resultIsRuntimeError = result?.code === 'ERR';
  const resultIsFailure = resultIsRuntimeError || resultCode === '0000';
  return (
    <div className="space-y-4">
      {currentLoadError ? (
        <div role="alert" className="p-3 rounded-lg border border-red-700 bg-red-950 bg-opacity-50 text-sm text-red-200">
          Failed to load DRG rule version {version}: {loadErrorMessage}
        </div>
      ) : !ruleSet ? (
        <div role="status" className="p-3 rounded-lg border dark-border bg-gray-800 text-sm text-gray-300">
          Loading DRG rule version {version}…
        </div>
      ) : null}
      <PatientInfoHeader showPatientInfo={showPatientInfo} onToggle={() => setShowPatientInfo(s => !s)} />
      {showPatientInfo && renderPatientInfoPanel()}
      <div className="border dark-border rounded-lg dark-surface-2 grid grid-cols-1 md:grid-cols-2 gap-0 items-stretch w-full">
        {renderCodeColumn('diagnosis')}
        {renderCodeColumn('procedure')}
      </div>
      <ActionButtons
        onGroupSingle={handleGroupSingle}
        onGroupAllOrders={handleGroupAllOrders}
        onClear={handleFlushAllConfirm}
        permRunning={permRunning}
        showAllOrders={!lite}
      />
      {!lite && permResults && (
        <div className="mt-4 p-4 dark-surface border dark-border rounded-lg">
          <h4 className="font-bold text-gray-100">Permutation Results</h4>
          {permResults.error ? (
            <div className="mt-2 rounded border border-red-700 bg-red-950 bg-opacity-50 p-3 text-sm text-red-200" role="alert">
              {permResults.description || permResults.error}
            </div>
          ) : (
            <>
              <div className="text-sm text-gray-300">Tried {permResults.processed} combos (available {permResults.totalCombos}). Found {permResults.results.length} distinct groupings.</div>
              <div className="mt-2 space-y-2">{permResults.results.map(renderPermutationCard)}</div>
            </>
          )}
        </div>
      )}
      {result && (
        <div
          ref={resultRef}
          tabIndex={-1}
          role={resultIsRuntimeError ? 'alert' : 'status'}
          aria-live={resultIsRuntimeError ? 'assertive' : 'polite'}
          aria-atomic="true"
          className={`mt-6 p-4 rounded-xl border-l-4 focus:outline-none ${resultIsFailure ? 'bg-error border-error' : 'bg-gray-900 border-success'}`}
        >
          <h3 className="text-lg font-bold mb-2 text-gray-100">Result</h3>
          <div className="flex flex-col items-start gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex min-w-0 flex-col items-start gap-2 sm:flex-row sm:items-center">
              <div className="shrink-0">
                <span className="block text-sm text-gray-300">DRG Code</span>
                <span className="text-2xl font-mono font-bold text-gray-100">{resultCode}</span>
              </div>
              <div className="min-w-0 sm:ml-2">
                <span className="block text-sm text-gray-300">Description</span>
                <div className="font-medium text-gray-100 break-words">{result.description}</div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {!lite && result.weight != null && (
                <div className="text-right">
                  <span className="block text-sm text-gray-300">基础点数（权重）</span>
                  <span className="text-2xl font-mono font-bold text-gray-100">{result.weight === '/' ? '特殊支付' : result.weight}</span>
                </div>
              )}
              {!lite && result.weightTier2 != null && (
                <div className="text-right">
                  <span className="block text-sm text-gray-300">{version.startsWith('cn-drg') ? '低风险死亡病组' : '二级医院权重'}</span>
                  <span className="text-2xl font-mono font-bold text-yellow-300">{result.weightTier2 === '/' ? version.startsWith('cn-drg') ? '是' : '特殊支付' : result.weightTier2}</span>
                </div>
              )}
            </div>
          </div>
          {result.matchTrace?.length ? (
            <GroupingTrace
              trace={result.matchTrace}
              principalProcedure={procedures[0]}
              onViewInMdcTree={onViewInMdcTree}
            />
          ) : null}
        </div>
      )}
    </div>
  );
}
