import { useState, useRef, useEffect, useMemo, useCallback } from 'react';
import { Trash2, ArrowUp } from 'lucide-react';
import { loadRuleSet, loadRuleSetAsync } from '../services/ruleSetLoader.js';
import { searchCodes } from '../services/CodeSearch';
import { convertGLtoYBCode } from '../services/CodeConversion';
import { buildPatientInfo, groupSingle, groupAllOrders } from '../services/singleEntry';
import { ensureSingleTrailingEmpty, reorderWithInfos, normalizeCodesAndInfos, namesSignificantlyDiffer } from './shared.jsx';
import { DEFAULT_RULE_VERSION } from '../services/generated/versionRegistry.js';
const createEmptyInfo = (overrides = {}) => ({ desc: '', type: '', searchResults: [], showDropdown: false, highlightedIndex: -1, ...overrides });
const normalizeInfoLength = (infos, targetLength) => {
  const next = [...(infos || [])];
  if (next.length > targetLength) next.splice(targetLength);
  while (next.length < targetLength) next.push(createEmptyInfo());
  return next;
};
// helper for keydown handlers: ignore events generated by an active IME
// composition session.  Browsers may indicate this with `isComposing` on the
// synthetic or native event or by emitting a `Process` key.  The input logic
// should simply return early when the user is still choosing characters.
function isIMEComposing(e) {
  if (!e) return false;
  if (e.isComposing) return true;
  if (e.nativeEvent && e.nativeEvent.isComposing) return true;
  if (e.key === 'Process') return true;
  return false;
}

function PatientInfoHeader({ showPatientInfo, onToggle }) {
  return (
    <div className="mt-4 flex items-center justify-between cursor-pointer select-none group py-1" onClick={onToggle} role="button" aria-expanded={showPatientInfo}>
      <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-widest">Patient Info</h3>
      <span className="text-gray-500 group-hover:text-gray-300 transition text-xs">{showPatientInfo ? '▲ Hide' : '▼ Show'}</span>
    </div>
  );
}
function ActionButtons({ onGroupSingle, onGroupAllOrders, onClear, permRunning, showAllOrders = true }) {
  return (
    <div className="mt-4 flex gap-2 items-center">
      <button
        onClick={onGroupSingle}
        className="flex-1 bg-blue-600 text-white py-2 px-3 rounded-xl text-base font-bold hover:bg-blue-700 active:scale-[0.98] transition shadow-md"
      >
        Group Patient
      </button>
      {showAllOrders && (
        <button
          onClick={onGroupAllOrders}
          className="flex-1 bg-gray-700 text-gray-100 py-2 px-3 rounded-xl text-sm font-medium hover:bg-gray-600 active:scale-[0.98] transition border border-gray-600 disabled:opacity-50"
          disabled={permRunning}
          title="Try all diagnosis/procedure orderings and report distinct DRG results"
        >
          {permRunning ? (
            <span className="flex items-center justify-center gap-2">
              <span className="inline-block w-3 h-3 border-2 border-gray-400 border-t-transparent rounded-full animate-spin" />
              Running…
            </span>
          ) : 'All Orders'}
        </button>
      )}
      <button
        onClick={onClear}
        className="px-3 py-2 rounded-xl text-sm font-medium text-red-400 hover:text-red-300 hover:bg-red-900 hover:bg-opacity-30 transition border border-transparent hover:border-red-800"
        title="Clear all inputs"
      >
        Clear
      </button>
    </div>
  );
}
export default function SingleTab({ searchSource, lite = false, version = DEFAULT_RULE_VERSION, codeIndexRevision = 0 }) {
  const [loadedRuleSet, setLoadedRuleSet] = useState(() => {
    try { return loadRuleSet(version); } catch { return null; }
  });
  useEffect(() => {
    let active = true;
    loadRuleSetAsync(version).then((nextRuleSet) => {
      if (active) setLoadedRuleSet(nextRuleSet);
    }).catch(() => {
      if (active) setLoadedRuleSet(null);
    });
    return () => { active = false; };
  }, [version]);
  const ruleSet = loadedRuleSet || loadRuleSet();
  const { loadCCCodes, loadMCCCodes, loadCCECodes, loadYBDiagNames, loadYBProcNames, isGrayDiag, isGrayProc, isInvalidDiagnosis, isInvalidProcedure } = ruleSet;
  const ybDiagNames = useMemo(() => loadYBDiagNames(), [loadYBDiagNames]);
  const ybProcNames = useMemo(() => loadYBProcNames(), [loadYBProcNames]);
  const ccIndex = useMemo(() => loadCCCodes() || {}, [loadCCCodes]);
  const mccIndex = useMemo(() => loadMCCCodes() || {}, [loadMCCCodes]);
  const excludeIndex = useMemo(() => loadCCECodes() || {}, [loadCCECodes]);
  const getCodeTagAndIndex = useCallback((code, kind = 'diagnosis', idx = 0) => {
    if (!code) return null;
    const normalizedCode = searchSource === 'GL' ? convertGLtoYBCode(code, false, version) : code;
    const tags = [];

    if (kind === 'procedure') {
      if (isInvalidProcedure(normalizedCode)) tags.push({ tag: 'INVALID' });
      if (isGrayProc(normalizedCode)) tags.push({ tag: 'GRAY' });
      if (!tags.length) return null;
      return { tags };
    }

    // diagnosis path
    if (isInvalidDiagnosis(normalizedCode)) tags.push({ tag: 'INVALID' });
    if (isGrayDiag(normalizedCode)) tags.push({ tag: 'GRAY' });
    if (idx === 0) {
      if (excludeIndex[normalizedCode]) tags.push({ tag: 'CCE', idx: excludeIndex[normalizedCode] });
    } else {
      if (mccIndex[normalizedCode]) tags.push({ tag: 'MCC', idx: mccIndex[normalizedCode] });
      if (ccIndex[normalizedCode]) tags.push({ tag: 'CC', idx: ccIndex[normalizedCode] });
    }

    if (!tags.length) return null;
    return { tags };
  }, [ccIndex, mccIndex, excludeIndex, searchSource, version, isGrayDiag, isGrayProc, isInvalidDiagnosis, isInvalidProcedure]);

  const [diagnoses, setDiagnoses] = useState(['']);
  const [procedures, setProcedures] = useState(['']);
  const [result, setResult] = useState(null);
  const [hasGrouped, setHasGrouped] = useState(false);
  const [patientGender, setPatientGender] = useState('1');
  const [patientAge, setPatientAge] = useState('30');
  const [patientAgeInDays, setPatientAgeInDays] = useState('');
  const [patientBirthWeight, setPatientBirthWeight] = useState('');
  const [patientDischargeStatus, setPatientDischargeStatus] = useState('alive');
  const [patientNewTechnique, setPatientNewTechnique] = useState(false);
  const [patientMultiSite, setPatientMultiSite] = useState(false);
  const [showPatientInfo, setShowPatientInfo] = useState(false);
  const [diagnosisInfos, setDiagnosisInfos] = useState([]);
  const [procedureInfos, setProcedureInfos] = useState([createEmptyInfo()]);
  const [permResults, setPermResults] = useState(null);
  const [permRunning, setPermRunning] = useState(false);
  const diagInputRefs = useRef([]);
  const procInputRefs = useRef([]);
  const prevSearchContextRef = useRef(null);
  const searchSourceRef = useRef(searchSource);
  const groupRequestRef = useRef(0);
  const setDiagRef = (el, idx) => { diagInputRefs.current[idx] = el; };
  const setProcRef = (el, idx) => { procInputRefs.current[idx] = el; };
  const focusDiagAt = (idx) => { const el = diagInputRefs.current[idx]; if (el && typeof el.focus === 'function') el.focus(); };
  const focusProcAt = (idx) => { const el = procInputRefs.current[idx]; if (el && typeof el.focus === 'function') el.focus(); };
  const getPatientInfo = useCallback(() => (
    buildPatientInfo
      ? buildPatientInfo({ gender: patientGender, age: patientAge, ageInDays: patientAgeInDays, birthWeight: patientBirthWeight, dischargeStatus: patientDischargeStatus, newTechnique: patientNewTechnique, multiSite: patientMultiSite })
      : { gender: patientGender }
  ), [patientGender, patientAge, patientAgeInDays, patientBirthWeight, patientDischargeStatus, patientNewTechnique, patientMultiSite]);
  const handlePatientAgeChange = (value) => {
    setPatientAge(value);
    if (String(value).trim() !== '') setPatientAgeInDays('');
  };
  const handlePatientAgeInDaysChange = (value) => {
    setPatientAgeInDays(value);
    if (String(value).trim() !== '') setPatientAge('');
  };

  useEffect(() => { searchSourceRef.current = searchSource; }, [searchSource]);

  const principalDiagnosisTag = useMemo(() => {
    const principal = Array.isArray(diagnoses) && diagnoses.length > 0 ? diagnoses[0] : '';
    return principal ? getCodeTagAndIndex(principal, 'diagnosis', 0) : null;
  }, [diagnoses, getCodeTagAndIndex]);

  const principalDiagnosisCCEId = useMemo(() => {
    if (!principalDiagnosisTag) return null;
    const tags = Array.isArray(principalDiagnosisTag.tags) ? principalDiagnosisTag.tags : [principalDiagnosisTag];
    const cce = tags.find((t) => t.tag === 'CCE');
    return cce ? cce.idx : null;
  }, [principalDiagnosisTag]);

  const handleListBlur = (kind, idx) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const setCodes = isDiagnosis ? setDiagnoses : setProcedures;
    const setInfos = isDiagnosis ? setDiagnosisInfos : setProcedureInfos;
    const searchType = isDiagnosis ? 'Diagnosis' : 'Procedure';
    setTimeout(() => {
      try {
        const value = (codes[idx] || '').toString().trim();
        const patch = {};
        if (value) {
          const results = searchCodes(value, searchType, searchSourceRef.current, version) || [];
          const exact = results.find(item => String(item.code || '').toLowerCase() === value.toLowerCase());
          if (exact) {
            patch.desc = exact.name || '';
            patch.type = exact.type || '';
          } else {
            patch.desc = '';
          }
        } else {
          patch.desc = '';
        }
        setInfos(prev => {
          const next = [...(prev || [])];
          if (!next[idx]) next[idx] = createEmptyInfo();
          next[idx] = { ...next[idx], ...patch, showDropdown: false };
          return next;
        });
      } catch {
        setInfos(prev => {
          const next = [...(prev || [])];
          if (next[idx]) next[idx] = { ...next[idx], showDropdown: false };
          return next;
        });
        return;
      }
      setCodes(prev => {
        const normalizedCodes = ensureSingleTrailingEmpty(prev);
        setInfos(prevInfos => normalizeInfoLength(prevInfos, normalizedCodes.length));
        return normalizedCodes;
      });
    }, 150);
  };


  const updateListInfo = useCallback((kind, idx, updater) => {
    const setInfos = kind === 'diagnosis' ? setDiagnosisInfos : setProcedureInfos;
    setInfos(prev => {
      const next = [...(prev || [])];
      const current = next[idx] || createEmptyInfo();
      next[idx] = updater(current);
      return next;
    });
  }, [setDiagnosisInfos, setProcedureInfos]);

  const handleListKeyDown = (kind, e, idx) => {
    // IME composition (pinyin) sends intermediary key events that should not
    // trigger navigation or selection.  Early-out when we detect an active
    // composition phase; this fixes complaints from Chinese users.
    if (isIMEComposing(e)) return;

    const isDiagnosis = kind === 'diagnosis';
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const setInfos = isDiagnosis ? setDiagnosisInfos : setProcedureInfos;
    const focusAt = isDiagnosis ? focusDiagAt : focusProcAt;
    const setCodes = isDiagnosis ? setDiagnoses : setProcedures;
    const idPrefix = isDiagnosis ? 'diag' : 'proc';
    const selectFn = (index, code, desc, type) => handleListSelect(kind, index, code, desc, type);

    const info = (infos && infos[idx]) || {};
    const results = (info.searchResults || []).slice(0, 20);
    const count = results.length;
    const highlighted = (typeof info.highlightedIndex === 'number') ? info.highlightedIndex : -1;
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (!count) return;
      const next = highlighted < 0 || highlighted >= count - 1 ? 0 : highlighted + 1;
      setInfos(prev => {
        const a = [...(prev || [])];
        if (!a[idx]) a[idx] = createEmptyInfo({ showDropdown: true });
        a[idx] = { ...a[idx], highlightedIndex: next, showDropdown: true };
        return a;
      });
      setTimeout(() => {
        const el = document.getElementById(`${idPrefix}-${idx}-item-${next}`);
        if (el && el.scrollIntoView) el.scrollIntoView({ block: 'nearest' });
      }, 0);
      return;
    }
    if (e.key === 'ArrowUp') {
      e.preventDefault();
      if (!count) return;
      const next = (highlighted <= 0) ? count - 1 : highlighted - 1;
      setInfos(prev => {
        const a = [...(prev || [])];
        if (!a[idx]) a[idx] = createEmptyInfo({ showDropdown: true });
        a[idx] = { ...a[idx], highlightedIndex: next, showDropdown: true };
        return a;
      });
      setTimeout(() => {
        const el = document.getElementById(`${idPrefix}-${idx}-item-${next}`);
        if (el && el.scrollIntoView) el.scrollIntoView({ block: 'nearest' });
      }, 0);
      return;
    }
    if (e.key === 'Escape') {
      e.preventDefault();
      setInfos(prev => {
        const a = [...(prev || [])];
        if (a[idx]) { a[idx].showDropdown = false; a[idx].highlightedIndex = -1; }
        return a;
      });
      return;
    }
    if (e.key === 'Enter') {
      e.preventDefault();
      if (info && info.searchResults && info.searchResults.length > 0) {
        const selIndex = (typeof info.highlightedIndex === 'number' && info.highlightedIndex >= 0) ? info.highlightedIndex : 0;
        const item = info.searchResults[selIndex];
        if (item) {
          selectFn(idx, item.code, item.name, item.type);
          setTimeout(() => focusAt(idx + 1), 50);
          return;
        }
      }
      setCodes(prev => {
        const n = ensureSingleTrailingEmpty(prev);
        setTimeout(() => focusAt(idx + 1), 50);
        return n;
      });
    }
  };

  const handleListRemove = (kind, index) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const setCodes = isDiagnosis ? setDiagnoses : setProcedures;
    const setInfos = isDiagnosis ? setDiagnosisInfos : setProcedureInfos;
    const nextCodes = [...codes];
    nextCodes.splice(index, 1);
    const normalized = ensureSingleTrailingEmpty(nextCodes);
    setCodes(normalized);
    setInfos((prev) => {
      const arr = [...(prev || [])];
      if (typeof index === 'number' && index >= 0 && index < arr.length) arr.splice(index, 1);
      return normalizeInfoLength(arr, normalized.length);
    });
  };

  // Move the given entry up to be the principal (index 0).
  const handleMoveToPrincipal = (kind, index) => {
    if (index === 0) return;
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const setCodes = isDiagnosis ? setDiagnoses : setProcedures;
    const setInfos = isDiagnosis ? setDiagnosisInfos : setProcedureInfos;
    const focusAt = isDiagnosis ? focusDiagAt : focusProcAt;

    setCodes(prev => {
      const { normalized } = reorderWithInfos(prev, infos, index, 0);
      return normalized;
    });
    setInfos(prev => {
      const { newInfos } = reorderWithInfos(codes, prev, index, 0);
      return newInfos;
    });

    // move focus to the new principal input so the user can continue typing
    setTimeout(() => focusAt(0), 50);
  };

  const handleListChange = (kind, index, val) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const searchType = isDiagnosis ? 'Diagnosis' : 'Procedure';
    const prevCodes = [...codes];
    const prevInfos = [...infos];
    prevCodes[index] = val;
    if (val.trim()) {
      const res = searchCodes(val.trim(), searchType, searchSourceRef.current, version);
      const existingDesc = (prevInfos[index] && prevInfos[index].desc) ? prevInfos[index].desc : '';
      prevInfos[index] = res && res.length ? createEmptyInfo({ desc: existingDesc, type: res[0].type, searchResults: res, showDropdown: true }) : createEmptyInfo({ desc: existingDesc });
    } else {
      prevInfos[index] = createEmptyInfo();
    }
    const normalized = normalizeCodesAndInfos(prevCodes, prevInfos);
    if (isDiagnosis) {
      setDiagnoses(normalized.codes);
      setDiagnosisInfos(normalized.infos);
    } else {
      setProcedures(normalized.codes);
      setProcedureInfos(normalized.infos);
    }
  };

  const handleListSelect = (kind, index, code, desc, type) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const prevCodes = [...codes];
    const prevInfos = [...infos];
    prevCodes[index] = code;
    prevInfos[index] = createEmptyInfo({ desc, type });
    const normalized = normalizeCodesAndInfos(prevCodes, prevInfos);
    if (isDiagnosis) {
      setDiagnoses(normalized.codes);
      setDiagnosisInfos(normalized.infos);
    } else {
      setProcedures(normalized.codes);
      setProcedureInfos(normalized.infos);
    }
  };
  const handleGroupSingle = useCallback(async () => {
    const requestId = ++groupRequestRef.current;
    const info = getPatientInfo();
    const out = groupSingle ? await groupSingle(diagnoses, procedures, info, searchSource, version) : null;
    if (requestId !== groupRequestRef.current) return;
    setHasGrouped(true);
    setPermResults(null);
    setPermRunning(false);
    if (out) {
      setResult({
        ...out.finalRes,
        diagnoses: out.diagnoses,
        procedures: out.procedures,
        diagnosesConverted: out.diagnosesConverted,
        proceduresConverted: out.proceduresConverted,
        conversionApplied: out.conversionApplied,
        patientInfo: out.patientInfo
      });
    }
  }, [diagnoses, procedures, getPatientInfo, searchSource, version]);
  const handleGroupSingleRef = useRef(handleGroupSingle);
  useEffect(() => {
    handleGroupSingleRef.current = handleGroupSingle;
  }, [handleGroupSingle]);

  const previousVersionRef = useRef(version);
  useEffect(() => {
    const previousVersion = previousVersionRef.current;
    previousVersionRef.current = version;
    if (previousVersion === version || !hasGrouped) return;
    handleGroupSingleRef.current();
  }, [version, hasGrouped]);

  const handleFlushAll = () => {
    groupRequestRef.current += 1;
    setHasGrouped(false);
    setDiagnoses(['']);
    setProcedures(['']);
    setDiagnosisInfos([createEmptyInfo()]);
    setProcedureInfos([createEmptyInfo()]);
    setPatientGender('1');
    setPatientAge('30');
    setPatientAgeInDays('');
    setPatientBirthWeight('');
    setPatientDischargeStatus('alive');
    setPatientNewTechnique(false);
    setPatientMultiSite(false);
    setShowPatientInfo(false);
    setResult(null);
    setPermResults(null);
    setPermRunning(false);
  };
  const handleFlushAllConfirm = () => {
    try {
      const ok = window.confirm('Flush all inputs? This will clear diagnoses, procedures, search state, and reset patient info. Continue?');
      if (!ok) return;
    } catch {
      // ignore confirm API failures
    }
    handleFlushAll();
  };
  const handleGroupAllOrders = async () => {
    const requestId = ++groupRequestRef.current;
    setResult(null);
    setPermRunning(true);
    setPermResults(null);
    const info = getPatientInfo();
    const out = groupAllOrders ? await groupAllOrders(diagnoses, procedures, info, searchSource, 720, version) : null;
    if (requestId !== groupRequestRef.current) return;
    if (out) setPermResults(out);
    setPermRunning(false);
  };

  useEffect(() => {
    const searchContext = `${version}:${searchSource}:${codeIndexRevision}`;
    if (prevSearchContextRef.current === searchContext) return;
    prevSearchContextRef.current = searchContext;

    const refreshInfosForSource = (codes, infos, setInfos, searchType) => {
      const nextInfos = normalizeInfoLength(infos, codes.length).map((info, idx) => {
        const code = (codes[idx] || '').toString().trim();
        if (!code) return createEmptyInfo();
        try {
          const results = searchCodes(code, searchType, searchSource, version) || [];
          const exact = results.find((item) => String(item.code || '').toLowerCase() === code.toLowerCase());
          if (!exact) return createEmptyInfo({ desc: '', type: '' });
          return createEmptyInfo({
            ...info,
            desc: exact.name || '',
            type: exact.type || '',
            searchResults: [],
            showDropdown: false,
            highlightedIndex: -1
          });
        } catch {
          return createEmptyInfo({
            ...info,
            searchResults: [],
            showDropdown: false,
            highlightedIndex: -1
          });
        }
      });
      setInfos(nextInfos);
    };

    refreshInfosForSource(diagnoses, diagnosisInfos, setDiagnosisInfos, 'Diagnosis');
    refreshInfosForSource(procedures, procedureInfos, setProcedureInfos, 'Procedure');
  }, [searchSource, version, codeIndexRevision, diagnoses, procedures, diagnosisInfos, procedureInfos]);

  const patientInfoFields = [
    {
      label: 'Gender',
      className: '',
      control: (
        <select value={patientGender} onChange={(e) => setPatientGender(e.target.value)} className="mt-1 w-full p-2 border dark-border rounded">
          <option value="1">Male</option>
          <option value="2">Female</option>
        </select>
      )
    },
    {
      label: 'Discharge Status',
      className: '',
      control: (
        <select value={patientDischargeStatus} onChange={(e) => setPatientDischargeStatus(e.target.value)} className="mt-1 w-full p-2 border dark-border rounded">
          <option value="alive">Alive</option>
          <option value="5">Dead</option>
        </select>
      )
    },
    {
      label: 'Age (years)',
      className: '',
      control: <input value={patientAge} onChange={(e) => handlePatientAgeChange(e.target.value)} placeholder="e.g. 0.5" className="mt-1 w-full p-2 border dark-border rounded" />
    },
    {
      label: 'Age (days)',
      className: '',
      control: <input value={patientAgeInDays} onChange={(e) => handlePatientAgeInDaysChange(e.target.value)} placeholder="e.g. 20" className="mt-1 w-full p-2 border dark-border rounded" />
    },
    {
      label: 'Birth weight (grams)',
      className: 'col-span-2',
      control: <input value={patientBirthWeight} onChange={(e) => setPatientBirthWeight(e.target.value)} placeholder="e.g. 3200" className="mt-1 w-full p-2 border dark-border rounded" />
    }
  ];

  const renderPatientInfoPanel = () => (
    <div className="mt-2 p-4 border dark-border rounded-lg dark-surface">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
        {patientInfoFields.map((field) => (
          <div key={field.label} className={field.className}>
            <label className="block text-sm text-gray-300 mb-1">{field.label}</label>
            {field.control}
          </div>
        ))}
        <div className="col-span-2 flex items-center mt-2">
          <input
            type="checkbox"
            id="newtechnique-checkbox"
            checked={patientNewTechnique}
            onChange={e => setPatientNewTechnique(e.target.checked)}
            className="mr-2 w-4 h-4"
          />
          <label htmlFor="newtechnique-checkbox" className="text-sm text-gray-300 select-none cursor-pointer">New Technique (新技术)</label>
        </div>
        <div className="col-span-2 flex items-center mt-2">
          <input
            type="checkbox"
            id="multisite-checkbox"
            checked={patientMultiSite}
            onChange={e => setPatientMultiSite(e.target.checked)}
            className="mr-2 w-4 h-4"
          />
          <label htmlFor="multisite-checkbox" className="text-sm text-gray-300 select-none cursor-pointer">Multi-site joint replacement (多部位关节置换)</label>
        </div>
      </div>
    </div>
  );

  const renderCodeTagBadge = (tagInfo, principalCCEId, compact = false) => {
    if (!tagInfo) return null;
    const tags = Array.isArray(tagInfo.tags) ? tagInfo.tags : [tagInfo];
    const wrapperClass = compact ? 'flex flex-wrap items-center gap-1' : 'flex flex-wrap items-center gap-2';
    const base = compact ? 'flex-shrink-0 px-2 py-0.5 rounded font-bold text-xs border ' : 'text-xs px-2 py-1 rounded font-bold border ';

    return (
      <span className={wrapperClass}>
        {tags.map((tagItem, index) => {
          const title = tagItem.tag === 'CCE' ? 'In CCE List' : tagItem.tag;
          const isPrincipalCCE = (tagItem.tag === 'MCC' || tagItem.tag === 'CC') && principalCCEId != null && tagItem.idx && String(tagItem.idx) === String(principalCCEId);
          const tagClasses = {
            INVALID: 'bg-red-100 border-red-300 text-red-700',
            GRAY: 'bg-amber-100 border-amber-300 text-amber-700',
            MCC: isPrincipalCCE ? 'bg-opacity-30 bg-gray-600 text-gray-200 border-gray-500' : 'bg-error border-error text-error',
            CC: isPrincipalCCE ? 'bg-opacity-30 bg-gray-600 text-gray-200 border-gray-500' : 'bg-warning border-warning text-warning'
          };
          const classes = base + (tagClasses[tagItem.tag] || 'bg-opacity-30 bg-gray-600 text-gray-200 border-gray-500');
          return (
            <span key={`${tagItem.tag}-${index}`} className={classes} title={title} aria-label={title}>
              {tagItem.tag}{tagItem.idx ? ` #${tagItem.idx}` : ''}
            </span>
          );
        })}
      </span>
    );
  };

  const getYBPreview = useCallback((item, isProcedure, ybNames) => {
    const preview = { showYB: false, ybCode: '', ybName: '', hasDifferentCode: false, hasDifferentName: false };
    try {
      if ((searchSource === 'GL' || item.source === 'GL') && item.code) {
        preview.ybCode = convertGLtoYBCode(item.code, isProcedure, version);
        if (preview.ybCode) {
          preview.ybName = (ybNames && ybNames[preview.ybCode]) ? ybNames[preview.ybCode] : '';
          preview.hasDifferentCode = preview.ybCode !== item.code;
          preview.hasDifferentName = !!preview.ybName && !!item.name && namesSignificantlyDiffer(item.name, preview.ybName);
          preview.showYB = preview.hasDifferentCode || preview.hasDifferentName;
        }
      }
    } catch {
      preview.showYB = false;
    }
    return preview;
  }, [searchSource, version]);

  const renderSearchDropdownItem = ({ kind, idx, i, item, highlightedIndex, isDiagnosis, principalCCEId, ybNames }) => {
    const tagInfo = getCodeTagAndIndex(item.code, isDiagnosis ? 'diagnosis' : 'procedure', idx);
    const { showYB, ybCode, ybName, hasDifferentCode, hasDifferentName } = getYBPreview(item, !isDiagnosis, ybNames);
    const tags = Array.isArray(tagInfo?.tags) ? tagInfo.tags : (tagInfo ? [tagInfo] : []);
    const isGray = tags.some((t) => t.tag === 'GRAY');
    const isInvalid = tags.some((t) => t.tag === 'INVALID');
    return (
      <div
        id={`${isDiagnosis ? 'diag' : 'proc'}-${idx}-item-${i}`}
        key={item.code + i}
        className={`px-3 py-2 cursor-pointer text-sm flex flex-col gap-1 transition border-l-2 ${highlightedIndex === i ? 'bg-blue-600 bg-opacity-20 border-blue-400' : 'border-transparent hover:bg-gray-700 hover:bg-opacity-60'}`}
        aria-selected={highlightedIndex === i}
        onMouseDown={() => handleListSelect(kind, idx, item.code, item.name, item.type)}
        onMouseEnter={() => updateListInfo(kind, idx, info => ({ ...info, showDropdown: true, highlightedIndex: i }))}
        onMouseLeave={() => updateListInfo(kind, idx, info => ({ ...info, highlightedIndex: -1 }))}
      >
        <div className="flex items-baseline gap-2 flex-wrap">
          <span className={`font-mono font-bold flex-shrink-0 ${isInvalid ? 'text-red-300' : isGray ? 'text-amber-300' : 'text-blue-400'}`}>{item.code}</span>
          <span className="text-gray-200">{item.name}</span>
          {renderCodeTagBadge(tagInfo, principalCCEId, true)}
          {showYB && (
            <>
              <span className="text-gray-600">→</span>
              {hasDifferentCode && <span className="font-mono text-xs text-gray-400">{ybCode}</span>}
              {hasDifferentName && <span className="text-xs text-gray-500">{ybName}</span>}
            </>
          )}
        </div>
      </div>
    );
  };

  const renderCodeColumn = (kind) => {
    const isDiagnosis = kind === 'diagnosis';
    const codes = isDiagnosis ? diagnoses : procedures;
    const infos = isDiagnosis ? diagnosisInfos : procedureInfos;
    const title = isDiagnosis ? 'Diagnoses' : 'Procedures';
    const principalCCEId = principalDiagnosisCCEId;
    const placeholderFor = (idx) => {
      if (isDiagnosis) return idx === 0 ? 'Principal Diagnosis (e.g. G40.909)' : 'Secondary Diagnosis';
      return idx === 0 ? 'Principal Procedure (e.g. 00.10)' : 'Procedure Code (e.g. 00.10)';
    };
    const setRef = isDiagnosis ? setDiagRef : setProcRef;
    const ybNames = isDiagnosis ? ybDiagNames : ybProcNames;

    return (
      <div className={`space-y-4 p-4 md:p-6 box-border ${isDiagnosis ? 'md:pr-8 md:border-r md:border-gray-200' : ''}`}>
        <div className={isDiagnosis ? 'flex justify-between items-end' : 'flex items-center justify-between'}><h2 className="text-xl font-bold text-gray-100">{title}</h2></div>
        {codes.map((code, idx) => {
          const entryName = infos[idx]?.desc || '';
          const tagInfo = getCodeTagAndIndex(code, isDiagnosis ? 'diagnosis' : 'procedure', idx);
          const tags = Array.isArray(tagInfo?.tags) ? tagInfo.tags : (tagInfo ? [tagInfo] : []);
          const isCodeGray = tags.some((t) => t.tag === 'GRAY');
          const isCodeInvalid = tags.some((t) => t.tag === 'INVALID');
          const inputYB = getYBPreview({ code, name: entryName, source: searchSource }, !isDiagnosis, ybNames);
          return (
            <div
              key={idx}
              data-idx={idx}
              className="flex flex-col gap-1 relative"
            >
              <div className="flex gap-2 items-center">
                <div className="flex-1 min-w-0 flex flex-col md:flex-row md:items-center gap-2">
                  <input
                    type="text"
                    placeholder={placeholderFor(idx)}
                    className={`flex-1 min-w-[13ch] p-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none ${isCodeGray ? 'text-amber-300 border-amber-400' : ''} ${isCodeInvalid ? 'text-red-300 border-red-400' : ''}`}
                    value={code}
                    onChange={(e) => handleListChange(kind, idx, e.target.value)}
                    ref={(el) => setRef(el, idx)}
                    onKeyDown={(e) => handleListKeyDown(kind, e, idx)}
                    autoComplete="off"
                    onFocus={() => updateListInfo(kind, idx, info => ({ ...info, showDropdown: true }))}
                    onBlur={() => handleListBlur(kind, idx)}
                  />
                  {(!!infos[idx]?.desc || !!tagInfo || inputYB.showYB) && (
                    <div className="flex flex-wrap items-center gap-1 mt-1 md:mt-0">
                      {infos[idx]?.desc && <span className="text-xs text-gray-300 dark-surface-2 p-1 rounded border dark-border break-words max-w-full">{infos[idx].desc}</span>}
                      {renderCodeTagBadge(tagInfo, principalCCEId)}
                      {inputYB.showYB && (
                        <>
                          <span className="text-gray-600">→</span>
                          {inputYB.hasDifferentCode && <span className="font-mono text-xs text-gray-400">{inputYB.ybCode}</span>}
                          {inputYB.hasDifferentName && <span className="text-xs text-gray-500">{inputYB.ybName}</span>}
                        </>
                      )}
                    </div>
                  )}
                </div>
                {idx > 0 && (
                  <button
                    onClick={() => handleMoveToPrincipal(kind, idx)}
                    className="p-2 text-blue-300 hover:bg-blue-700 hover:bg-opacity-50 rounded-sm transition"
                    aria-label={`Make ${isDiagnosis ? 'diagnosis' : 'procedure'} principal`}
                    title="Make principal"
                  >
                    <ArrowUp size={14} />
                  </button>
                )}
                <button
                  onClick={() => handleListRemove(kind, idx)}
                  className="p-2 text-red-400 hover:bg-error hover:bg-opacity-50 rounded-sm transition"
                  aria-label={`Remove ${isDiagnosis ? 'diagnosis' : 'procedure'}`}
                >
                  <Trash2 size={14} />
                </button>
              </div>
              {infos[idx]?.showDropdown && infos[idx]?.searchResults?.length > 0 && (
                <div className="absolute z-10 top-full left-0 w-full bg-gray-900 border border-gray-700 rounded shadow-xl max-h-64 overflow-auto">
                  {infos[idx].searchResults.slice(0, 20).map((item, i) => renderSearchDropdownItem({
                    kind,
                    idx,
                    i,
                    item,
                    highlightedIndex: infos[idx].highlightedIndex,
                    isDiagnosis,
                    principalCCEId,
                    ybNames
                  }))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    );
  };

  const renderPermutationCard = (r, idx) => (
    <div key={idx} className="p-2 border dark-border rounded dark-surface-2">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="font-mono font-bold text-lg text-blue-400">{r.summary.drg || r.summary.key}</div>
          <div className="text-sm text-gray-200">{r.summary.description || '-'}</div>
        </div>
        <div className="flex items-center gap-2">
          {r.summary.weight != null && <div className="text-sm font-mono font-semibold text-blue-300">{r.summary.weight === '/' ? '特殊支付' : r.summary.weight}</div>}
          {r.summary.weightTier2 != null && <div className="text-sm font-mono font-semibold text-yellow-300">{r.summary.weightTier2 === '/' ? '特殊支付' : r.summary.weightTier2}</div>}
        </div>
      </div>
      <div className="text-xs mt-1 text-gray-400">Examples ({r.examples.length}):</div>
      <div className="text-xs text-gray-300">
        {r.examples.slice(0, 3).map((ex, i) => {
          const pd = ex.diagnoses && ex.diagnoses.length ? ex.diagnoses[0] : '';
          const pp = ex.procedures && ex.procedures.length ? ex.procedures[0] : '';
          return (
            <div key={i} className="truncate">diag: [{pd}] proc: [{pp}]</div>
          );
        })}
      </div>
    </div>
  );
  const renderTraceSectionDetail = (step) => {
    if (!(step.detail || step.status)) return null;
    return (
      <div className="mt-1 text-xs text-gray-300 pl-3 border-l-2 border-gray-500">
        {step.status && (
          <div>
            Level: <span className="font-bold">{step.status.toUpperCase()}</span>
          </div>
        )}
        {step.detail?.message && <div className="italic">{step.detail.message}</div>}
        {step.detail?.reason && <div className="italic">{step.detail.reason}</div>}
        {step.detail?.details?.sections && (
          <div className="mt-1 space-y-1">
            {Object.entries(step.detail.details.sections).map(([name, res]) => (
              <div key={name} className={`p-1 rounded ${res.matched ? 'text-success' : 'text-gray-400'}`}>
                <div className="flex items-center gap-2">
                  <span className="font-bold">{res.matched ? '●' : '○'}</span>
                  <span className="font-medium">{name}</span>
                </div>
                <div className="text-xs ml-5 mt-1">
                  {Array.isArray(res.matchedCodes) && res.matchedCodes.length > 0
                    ? <div>Matched codes: <span className="font-mono">{res.matchedCodes.join(', ')}</span></div>
                    : <div className="text-gray-400">No matching codes</div>}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  };
  const renderTraceStep = (step, idx) => (
    <div
      key={idx}
      className={`p-2 rounded-lg border flex flex-col gap-1 ${step.matched ? 'bg-success-muted border-success' : (step.matched === false ? 'bg-error-muted border-error' : 'bg-gray-800 border-gray-600')}`}
    >
      <div className="flex justify-between items-center">
        <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-gray-700 border-gray-600 border text-gray-300">{step.stage}</span>
        {step.matched !== undefined && (
          <span className={`text-[10px] font-bold ${step.matched ? 'text-success' : 'text-error'}`}>
            {step.matched ? '✓ Match' : '✗ No Match'}
          </span>
        )}
      </div>
      <div className="font-medium text-sm flex items-baseline gap-2">
        {step.code && <span className="font-mono font-bold text-blue-400">{step.code}</span>}
        <span className="text-gray-200">{step.description}</span>
      </div>
      {renderTraceSectionDetail(step)}
    </div>
  );
  return (
    <div className="space-y-4">
      <PatientInfoHeader showPatientInfo={showPatientInfo} onToggle={() => setShowPatientInfo(s => !s)} />
      {showPatientInfo && renderPatientInfoPanel()}
      <div className="border dark-border rounded-lg dark-surface-2 grid grid-cols-1 md:grid-cols-2 gap-0 items-stretch w-full">
        {renderCodeColumn('diagnosis')}
        {renderCodeColumn('procedure')}
      </div>
      <ActionButtons
        onGroupSingle={handleGroupSingle}
        onGroupAllOrders={handleGroupAllOrders}
        onClear={handleFlushAllConfirm}
        permRunning={permRunning}
        showAllOrders={!lite}
      />
      {!lite && permResults && (
        <div className="mt-4 p-4 dark-surface border dark-border rounded-lg">
          <h4 className="font-bold text-gray-100">Permutation Results</h4>
          {permResults.error ? (
            <div className="mt-2 rounded border border-red-700 bg-red-950 bg-opacity-50 p-3 text-sm text-red-200" role="alert">
              {permResults.description || permResults.error}
            </div>
          ) : (
            <>
              <div className="text-sm text-gray-300">Tried {permResults.processed} combos (available {permResults.totalCombos}). Found {permResults.results.length} distinct groupings.</div>
              <div className="mt-2 space-y-2">{permResults.results.map(renderPermutationCard)}</div>
            </>
          )}
        </div>
      )}
      {result && (
        <div className={`mt-6 p-4 rounded-xl border-l-4 ${result.code === 'ERR' ? 'bg-error border-error' : 'bg-success border-success'}`}>
          <h3 className="text-lg font-bold mb-2 text-gray-100">Result</h3>
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div>
                <span className="block text-sm text-gray-300">DRG Code</span>
                <span className="text-2xl font-mono font-bold text-gray-100">{result.drg || result.code}</span>
              </div>
              <div className="ml-2">
                <span className="block text-sm text-gray-300">Description</span>
                <div className="font-medium text-gray-100">{result.description}</div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {!lite && result.weight != null && (
                <div className="text-right">
                  <span className="block text-sm text-gray-300">基础点数（权重）</span>
                  <span className="text-2xl font-mono font-bold text-gray-100">{result.weight === '/' ? '特殊支付' : result.weight}</span>
                </div>
              )}
              {!lite && result.weightTier2 != null && (
                <div className="text-right">
                  <span className="block text-sm text-gray-300">{version.startsWith('cn-drg') ? '低风险死亡病组' : '二级医院权重'}</span>
                  <span className="text-2xl font-mono font-bold text-yellow-300">{result.weightTier2 === '/' ? version.startsWith('cn-drg') ? '是' : '特殊支付' : result.weightTier2}</span>
                </div>
              )}
            </div>
          </div>
          {result.matchTrace && (
            <div className="mt-6 space-y-3">
              <h4 className="text-sm font-bold text-gray-200 tracking-wider">Grouping Trace</h4>
              <div className="space-y-2">{result.matchTrace.map(renderTraceStep)}</div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
